# Generated by Django 5.0.14 on 2025-11-22 18:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_number", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["form_number"],
            },
        ),
        migrations.CreateModel(
            name="LearningArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OAuthCredentialStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100, unique=True)),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("refresh_token", models.TextField()),
                ("access_token", models.TextField(blank=True, null=True)),
                (
                    "token_uri",
                    models.CharField(
                        default="https://oauth2.googleapis.com/token", max_length=255
                    ),
                ),
                ("scopes", models.JSONField(default=list)),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuizCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Midterm Exam', 'Practice Quiz')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the category",
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for UI display (e.g., #3B82F6)",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class name for UI (e.g., 'fa-book', 'bi-book')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quiz Category",
                "verbose_name_plural": "Quiz Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("superadmin", "Super Administrator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_superadmin", models.BooleanField(default=False)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="quiz_center_users", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="quiz_center_users",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("name", models.CharField(max_length=20)),
                ("maximum_students", models.SmallIntegerField(default=40)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.academicyear",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz_app.form",
                    ),
                ),
                (
                    "learning_area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz_app.learningarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiz_id",
                    models.CharField(
                        editable=False,
                        help_text="Unique quiz identifier",
                        max_length=15,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Quiz title (e.g., 'Mathematics Midterm Exam')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the quiz",
                        null=True,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instructions for students taking the quiz",
                        null=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier",
                        max_length=220,
                        unique=True,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        help_text="Overall difficulty level of the quiz",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Current status of the quiz",
                        max_length=10,
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=60, help_text="Time limit in minutes (0 for unlimited)"
                    ),
                ),
                (
                    "total_marks",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total marks for the quiz (auto-calculated)",
                    ),
                ),
                (
                    "passing_marks",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum marks required to pass"
                    ),
                ),
                (
                    "available_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when quiz becomes available",
                        null=True,
                    ),
                ),
                (
                    "available_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when quiz becomes unavailable",
                        null=True,
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of attempts allowed per student",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "randomize_questions",
                    models.BooleanField(
                        default=False,
                        help_text="Randomize question order for each attempt",
                    ),
                ),
                (
                    "randomize_answers",
                    models.BooleanField(
                        default=False, help_text="Randomize answer choices order"
                    ),
                ),
                (
                    "show_results_immediately",
                    models.BooleanField(
                        default=True,
                        help_text="Show results immediately after submission",
                    ),
                ),
                (
                    "show_correct_answers",
                    models.BooleanField(
                        default=True, help_text="Show correct answers after completion"
                    ),
                ),
                (
                    "allow_review",
                    models.BooleanField(
                        default=True, help_text="Allow students to review their answers"
                    ),
                ),
                (
                    "require_password",
                    models.BooleanField(
                        default=False, help_text="Require password to access quiz"
                    ),
                ),
                (
                    "quiz_password",
                    models.CharField(
                        blank=True,
                        help_text="Password to access quiz",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this quiz is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        help_text="Academic year this quiz belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="quiz_app.academicyear",
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Classes assigned to take this quiz",
                        related_name="assigned_quizzes",
                        to="quiz_app.class",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category for organizing quizzes",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="quiz_app.quizcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "short_name",
                    models.CharField(
                        help_text="Abbreviation or short name of the school",
                        max_length=20,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="default-school",
                        help_text="URL-friendly version of the school name, used in subdomains",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("address", models.TextField()),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "school_code",
                    models.CharField(
                        blank=True,
                        help_text="Official school code/ID",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/school_image/"
                    ),
                ),
                (
                    "school_stamp",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/school_image/"
                    ),
                ),
                (
                    "report_header",
                    models.TextField(
                        blank=True,
                        help_text="Custom header text for reports",
                        null=True,
                    ),
                ),
                (
                    "report_footer",
                    models.TextField(
                        blank=True,
                        help_text="Custom footer text for reports",
                        null=True,
                    ),
                ),
                ("motto", models.CharField(blank=True, max_length=200, null=True)),
                ("vision", models.TextField(blank=True, null=True)),
                ("mission", models.TextField(blank=True, null=True)),
                (
                    "grading_system_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the grading system to appear on reports",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_school_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_for_school",
                        to="quiz_app.academicyear",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_school_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "School Information",
                "verbose_name_plural": "School Information",
            },
        ),
        migrations.AddField(
            model_name="quizcategory",
            name="school",
            field=models.ForeignKey(
                help_text="School this category belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_categories",
                to="quiz_app.schoolinformation",
            ),
        ),
        migrations.CreateModel(
            name="QuizAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of attempts"
                    ),
                ),
                (
                    "completed_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of completed attempts"
                    ),
                ),
                (
                    "unique_students",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of unique students who attempted"
                    ),
                ),
                (
                    "average_score",
                    models.FloatField(
                        default=0,
                        help_text="Average score across all completed attempts",
                    ),
                ),
                (
                    "highest_score",
                    models.FloatField(default=0, help_text="Highest score achieved"),
                ),
                (
                    "lowest_score",
                    models.FloatField(default=0, help_text="Lowest score achieved"),
                ),
                (
                    "median_score",
                    models.FloatField(default=0, help_text="Median score"),
                ),
                (
                    "pass_rate",
                    models.FloatField(
                        default=0, help_text="Percentage of students who passed"
                    ),
                ),
                (
                    "average_time_taken",
                    models.DurationField(
                        blank=True,
                        help_text="Average time taken to complete",
                        null=True,
                    ),
                ),
                (
                    "fastest_completion",
                    models.DurationField(
                        blank=True, help_text="Fastest completion time", null=True
                    ),
                ),
                (
                    "slowest_completion",
                    models.DurationField(
                        blank=True, help_text="Slowest completion time", null=True
                    ),
                ),
                (
                    "grade_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Distribution of grades (A+, A, B, C, D, F)",
                    ),
                ),
                (
                    "question_analytics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed analytics per question",
                    ),
                ),
                (
                    "performance_trends",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Performance trends over time (for charts)",
                    ),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(
                        auto_now=True, help_text="When analytics were last calculated"
                    ),
                ),
                (
                    "quiz",
                    models.OneToOneField(
                        help_text="Quiz these analytics belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="quiz_app.quiz",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School these analytics belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_analytics",
                        to="quiz_app.schoolinformation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Analytics",
                "verbose_name_plural": "Quiz Analytics",
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="school",
            field=models.ForeignKey(
                help_text="School this quiz belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="quiz_app.schoolinformation",
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_id",
                    models.CharField(
                        editable=False,
                        help_text="Unique question identifier",
                        max_length=15,
                        unique=True,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("fill_blank", "Fill in the Blank"),
                            ("matching", "Matching"),
                            ("ordering", "Ordering"),
                        ],
                        help_text="Type of question (multiple choice, essay, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "question_text",
                    models.TextField(help_text="The question text/content"),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation shown after answering (for feedback)",
                        null=True,
                    ),
                ),
                (
                    "correct_answer_text",
                    models.TextField(
                        blank=True,
                        help_text="Correct answer for short answer/fill in blank questions (can be multiple answers separated by semicolons)",
                        null=True,
                    ),
                ),
                (
                    "marks",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Marks awarded for correct answer",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "negative_marks",
                    models.FloatField(
                        default=0,
                        help_text="Marks deducted for wrong answer (negative marking)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "partial_credit",
                    models.BooleanField(
                        default=False,
                        help_text="Allow partial credit for partially correct answers",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        help_text="Difficulty level of this question",
                        max_length=10,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this question is required to answer",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within the quiz"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorizing questions (e.g., ['algebra', 'geometry'])",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image associated with the question",
                        null=True,
                        upload_to="quiz_questions/",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Audio file for the question (if applicable)",
                        null=True,
                        upload_to="quiz_questions/audio/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        help_text="Quiz this question belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz_app.quiz",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School this question belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="quiz_app.schoolinformation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="learningarea",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_areas",
                to="quiz_app.schoolinformation",
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="quiz_app.schoolinformation",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="quiz_app.schoolinformation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="class",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="quiz_app.schoolinformation",
            ),
        ),
        migrations.CreateModel(
            name="AnswerChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_text",
                    models.CharField(
                        help_text="The text content of this answer choice",
                        max_length=500,
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, help_text="Whether this is the correct answer"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order of this choice"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation for why this choice is correct/incorrect",
                        null=True,
                    ),
                ),
                (
                    "partial_credit",
                    models.FloatField(
                        default=0.0,
                        help_text="Partial credit (0.0 to 1.0) if this choice is selected (for partial credit questions)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question this answer choice belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_choices",
                        to="quiz_app.question",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School this answer choice belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_choices",
                        to="quiz_app.schoolinformation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Choice",
                "verbose_name_plural": "Answer Choices",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="academicyear",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="quiz_app.schoolinformation",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="quiz_app.schoolinformation",
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_number", models.CharField(max_length=10, unique=True)),
                ("full_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("parent_contact", models.CharField(max_length=15)),
                ("admission_date", models.DateField()),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/students/"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz_app.form",
                    ),
                ),
                (
                    "learning_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz_app.learningarea",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="quiz_app.schoolinformation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="student_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quiz_app.student",
            ),
        ),
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_assigned", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz_app.class"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_classes",
                        to="quiz_app.schoolinformation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_code",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("subject_name", models.CharField(max_length=100)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.department",
                    ),
                ),
                (
                    "learning_area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz_app.learningarea",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="quiz_app.schoolinformation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quiz",
            name="subject",
            field=models.ForeignKey(
                help_text="Subject this quiz belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="quiz_app.subject",
            ),
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_subject_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.academicyear",
                    ),
                ),
                (
                    "class_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz_app.class"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="quiz_app.schoolinformation",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "staff_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/teachers/"
                    ),
                ),
                (
                    "skip_user_creation",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz_app.department",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="quiz_app.schoolinformation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quiz",
            name="teacher",
            field=models.ForeignKey(
                help_text="Teacher who created this quiz",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_quizzes",
                to="quiz_app.teacher",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="head_of_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_department",
                to="quiz_app.teacher",
            ),
        ),
        migrations.CreateModel(
            name="ClassTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_assigned", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.academicyear",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz_app.class"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_teachers",
                        to="quiz_app.schoolinformation",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.teacher",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="teacher_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quiz_app.teacher",
            ),
        ),
        migrations.CreateModel(
            name="TeacherSubjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("date_assigned", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("assignment_history", models.JSONField(blank=True, default=list)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.academicyear",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz_app.class"
                    ),
                ),
                (
                    "previous_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_assignments",
                        to="quiz_app.teacher",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_subject_assignments",
                        to="quiz_app.schoolinformation",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term_number",
                    models.SmallIntegerField(
                        choices=[
                            (1, "First Term"),
                            (2, "Second Term"),
                            (3, "Third Term"),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="quiz_app.schoolinformation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schoolinformation",
            name="current_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_school",
                to="quiz_app.term",
            ),
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_id",
                    models.CharField(
                        editable=False,
                        help_text="Unique attempt identifier",
                        max_length=15,
                        unique=True,
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Attempt number for this student (1st, 2nd, etc.)",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the attempt was started"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the attempt was completed",
                        null=True,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the attempt was submitted",
                        null=True,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0,
                        help_text="Total score achieved",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "percentage",
                    models.FloatField(
                        default=0,
                        help_text="Percentage score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of questions in the quiz"
                    ),
                ),
                (
                    "correct_answers",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of correct answers"
                    ),
                ),
                (
                    "wrong_answers",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of wrong answers"
                    ),
                ),
                (
                    "unanswered",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of unanswered questions"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Whether the attempt is completed"
                    ),
                ),
                (
                    "is_submitted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the attempt has been submitted",
                    ),
                ),
                (
                    "time_taken",
                    models.DurationField(
                        blank=True,
                        help_text="Total time taken for the attempt",
                        null=True,
                    ),
                ),
                (
                    "needs_grading",
                    models.BooleanField(
                        default=False,
                        help_text="Whether manual grading is required (for essay questions)",
                    ),
                ),
                (
                    "is_graded",
                    models.BooleanField(
                        default=False,
                        help_text="Whether all questions have been graded",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the student", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Browser user agent string", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes or comments about this attempt (for teachers)",
                        null=True,
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        help_text="Academic year when attempt was made",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_attempts",
                        to="quiz_app.academicyear",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        help_text="Quiz being attempted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quiz_app.quiz",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School this attempt belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="quiz_app.schoolinformation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student making this attempt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="quiz_app.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        help_text="Term when attempt was made",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_attempts",
                        to="quiz_app.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Attempt",
                "verbose_name_plural": "Quiz Attempts",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="term",
            field=models.ForeignKey(
                blank=True,
                help_text="Term this quiz belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizzes",
                to="quiz_app.term",
            ),
        ),
        migrations.CreateModel(
            name="SchoolAuthoritySignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authority_type",
                    models.CharField(
                        choices=[
                            ("headmaster", "Headmaster/Principal"),
                            ("academic_head", "Academic Headmaster"),
                            ("deputy_head", "Deputy Headmaster"),
                            ("exam_officer", "Examination Officer"),
                            ("other", "Other Authority"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("signature", models.ImageField(upload_to="static/signatures/")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "custom_title",
                    models.CharField(
                        blank=True,
                        help_text="Custom title if 'Other Authority' is selected",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authority_signatures",
                        to="quiz_app.schoolinformation",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Authority Signature",
                "verbose_name_plural": "School Authority Signatures",
                "unique_together": {("school", "authority_type")},
            },
        ),
        migrations.CreateModel(
            name="QuizResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_id",
                    models.CharField(
                        editable=False,
                        help_text="Unique response identifier",
                        max_length=15,
                        unique=True,
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(
                        blank=True,
                        help_text="Text answer (for short answer/essay questions)",
                        null=True,
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, help_text="Whether the response is correct"
                    ),
                ),
                (
                    "marks_awarded",
                    models.FloatField(
                        default=0, help_text="Marks awarded for this response"
                    ),
                ),
                (
                    "is_graded",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this response has been manually graded",
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, help_text="When this response was graded", null=True
                    ),
                ),
                (
                    "grading_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes or feedback from the grader",
                        null=True,
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the response was submitted"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the response was last updated"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        help_text="Quiz attempt this response belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="quiz_app.quizattempt",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher who graded this response",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Question being answered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="quiz_app.question",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected answer choice (for multiple choice/true-false)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_app.answerchoice",
                    ),
                ),
                (
                    "selected_choices",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Multiple selected choices (for questions with multiple correct answers)",
                        related_name="responses",
                        to="quiz_app.answerchoice",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School this response belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_responses",
                        to="quiz_app.schoolinformation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Response",
                "verbose_name_plural": "Quiz Responses",
                "indexes": [
                    models.Index(
                        fields=["attempt", "question"],
                        name="quiz_app_qu_attempt_ecd8a2_idx",
                    ),
                    models.Index(
                        fields=["question", "is_correct"],
                        name="quiz_app_qu_questio_02254d_idx",
                    ),
                    models.Index(
                        fields=["is_graded", "is_correct"],
                        name="quiz_app_qu_is_grad_ca3be1_idx",
                    ),
                    models.Index(
                        fields=["school", "answered_at"],
                        name="quiz_app_qu_school__f56f47_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="quizresponse",
            constraint=models.CheckConstraint(
                check=models.Q(("marks_awarded__gte", -100)),
                name="marks_awarded_reasonable",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizresponse",
            unique_together={("attempt", "question")},
        ),
        migrations.AddIndex(
            model_name="quizcategory",
            index=models.Index(
                fields=["school", "is_active"], name="quiz_app_qu_school__b5a790_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizcategory",
            index=models.Index(
                fields=["name", "school"], name="quiz_app_qu_name_05d57a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizcategory",
            unique_together={("name", "school")},
        ),
        migrations.AddIndex(
            model_name="quizanalytics",
            index=models.Index(fields=["quiz"], name="quiz_app_qu_quiz_id_6a8151_idx"),
        ),
        migrations.AddIndex(
            model_name="quizanalytics",
            index=models.Index(
                fields=["school", "last_calculated"],
                name="quiz_app_qu_school__861ced_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["quiz", "order"], name="quiz_app_qu_quiz_id_d017bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_type"], name="quiz_app_qu_questio_44aff0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty"], name="quiz_app_qu_difficu_736e81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["school"], name="quiz_app_qu_school__4cc420_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                check=models.Q(("marks__gte", 1)), name="question_marks_at_least_one"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                check=models.Q(("negative_marks__gte", 0)),
                name="negative_marks_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="learningarea",
            index=models.Index(fields=["code"], name="quiz_app_le_code_e19fa4_idx"),
        ),
        migrations.AddIndex(
            model_name="learningarea",
            index=models.Index(
                fields=["school", "code"], name="quiz_app_le_school__6fb4b9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="learningarea",
            unique_together={("code", "school")},
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(
                fields=["form_number"], name="quiz_app_fo_form_nu_9cfee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(
                fields=["school", "form_number"], name="quiz_app_fo_school__149201_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="form",
            unique_together={("form_number", "school")},
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(fields=["name"], name="quiz_app_cl_name_975609_idx"),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(fields=["form"], name="quiz_app_cl_form_id_c44336_idx"),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["learning_area"], name="quiz_app_cl_learnin_bfdb8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["academic_year"], name="quiz_app_cl_academi_f3e84f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["school"], name="quiz_app_cl_school__4711a9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.UniqueConstraint(
                fields=("name", "academic_year"), name="unique_class_name_academic_year"
            ),
        ),
        migrations.AddIndex(
            model_name="answerchoice",
            index=models.Index(
                fields=["question", "order"], name="quiz_app_an_questio_ab53b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answerchoice",
            index=models.Index(
                fields=["question", "is_correct"], name="quiz_app_an_questio_059809_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="answerchoice",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("partial_credit__gte", 0.0), ("partial_credit__lte", 1.0)
                ),
                name="partial_credit_range",
            ),
        ),
        migrations.AddIndex(
            model_name="academicyear",
            index=models.Index(
                fields=["is_current"], name="quiz_app_ac_is_curr_54ace0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicyear",
            index=models.Index(
                fields=["school", "is_current"], name="quiz_app_ac_school__d4f41a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicyear",
            unique_together={("name", "school")},
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["admission_number"], name="quiz_app_st_admissi_ecd816_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["learning_area"], name="quiz_app_st_learnin_7c4f26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["form"], name="quiz_app_st_form_id_8ff2f4_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school"], name="quiz_app_st_school__b0f95d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclass",
            index=models.Index(
                fields=["student", "is_active"], name="quiz_app_st_student_8a8de2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclass",
            index=models.Index(
                fields=["assigned_class", "is_active"],
                name="quiz_app_st_assigne_f89ab7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclass",
            index=models.Index(
                fields=["student", "assigned_class", "is_active"],
                name="quiz_app_st_student_dd7912_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclass",
            index=models.Index(
                fields=["school", "is_active"], name="quiz_app_st_school__c214d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["learning_area"], name="quiz_app_su_learnin_209ea1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["department"], name="quiz_app_su_departm_24289c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["school"], name="quiz_app_su_school__f2aa54_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("subject_code", "school")},
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["subject"], name="quiz_app_cl_subject_8e8bb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["class_name"], name="quiz_app_cl_class_n_98bbb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["academic_year"], name="quiz_app_cl_academi_208151_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["school"], name="quiz_app_cl_school__c5d7dc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="classsubject",
            constraint=models.UniqueConstraint(
                fields=("subject", "class_name", "academic_year"),
                name="unique_class_subject",
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["staff_id"], name="quiz_app_te_staff_i_04487d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["school"], name="quiz_app_te_school__173979_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["department"], name="quiz_app_te_departm_ca8ea2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="quiz_app_de_code_2e7e08_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["school", "code"], name="quiz_app_de_school__4fb653_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("code", "school")},
        ),
        migrations.AddIndex(
            model_name="classteacher",
            index=models.Index(
                fields=["teacher", "is_active"], name="quiz_app_cl_teacher_7a699c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classteacher",
            index=models.Index(
                fields=["class_assigned", "academic_year", "is_active"],
                name="quiz_app_cl_class_a_95b9a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classteacher",
            index=models.Index(
                fields=["academic_year", "is_active"],
                name="quiz_app_cl_academi_1c9c8a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classteacher",
            index=models.Index(
                fields=["school", "is_active"], name="quiz_app_cl_school__32fc0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["teacher", "is_active"], name="quiz_app_te_teacher_0d76e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["class_assigned", "subject", "is_active"],
                name="quiz_app_te_class_a_ffaffd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["academic_year", "is_active"],
                name="quiz_app_te_academi_b5e112_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["subject", "class_assigned", "academic_year", "is_active"],
                name="quiz_app_te_subject_b5e463_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["school", "is_active"], name="quiz_app_te_school__ad510b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(
                fields=["is_current"], name="quiz_app_te_is_curr_394274_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(
                fields=["academic_year", "is_current"],
                name="quiz_app_te_academi_280d6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(
                fields=["school", "is_current"], name="quiz_app_te_school__9fc2db_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "term_number"), name="unique_term"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["quiz", "student"], name="quiz_app_qu_quiz_id_73fe00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["student", "started_at"], name="quiz_app_qu_student_9edcb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["quiz", "is_completed"], name="quiz_app_qu_quiz_id_5c7c40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["school", "started_at"], name="quiz_app_qu_school__a2fd09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["academic_year", "term"], name="quiz_app_qu_academi_02839d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["is_submitted", "needs_grading"],
                name="quiz_app_qu_is_subm_5161dd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizattempt",
            constraint=models.CheckConstraint(
                check=models.Q(("score__gte", 0)), name="attempt_score_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="quizattempt",
            constraint=models.CheckConstraint(
                check=models.Q(("percentage__gte", 0), ("percentage__lte", 100)),
                name="percentage_range",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizattempt",
            unique_together={("quiz", "student", "attempt_number")},
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["subject", "status"], name="quiz_app_qu_subject_5b8f44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["teacher", "status"], name="quiz_app_qu_teacher_3dd145_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["school", "status"], name="quiz_app_qu_school__ec31a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["academic_year", "term", "status"],
                name="quiz_app_qu_academi_0a557a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["available_from", "available_until"],
                name="quiz_app_qu_availab_f5a636_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["status", "is_active"], name="quiz_app_qu_status_0453fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["created_at"], name="quiz_app_qu_created_e514a2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quiz",
            constraint=models.CheckConstraint(
                check=models.Q(("passing_marks__lte", models.F("total_marks"))),
                name="passing_marks_not_exceed_total",
            ),
        ),
    ]
