# Generated by Django 5.0.14 on 2025-11-26 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="quiz_app.schoolinformation",
            ),
        ),
    ]
