#!/bin/bash
# Quick setup script for hostname configuration on Linux/Mac
# This script helps you configure the Django app to use a hostname

echo "========================================"
echo "Django Quiz App - Hostname Configuration"
echo "========================================"
echo ""

# Get hostname
SERVER_HOSTNAME=$(hostname)
echo "Detected hostname: $SERVER_HOSTNAME"
echo ""

# Get IP address
IP_ADDRESS=$(hostname -I | awk '{print $1}')
if [ -z "$IP_ADDRESS" ]; then
    IP_ADDRESS=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr eth0 2>/dev/null || echo "192.168.1.100")
fi
echo "Detected IP address: $IP_ADDRESS"
echo ""

# Prompt for custom hostname
read -p "Enter your desired hostname (or press Enter to use $SERVER_HOSTNAME): " CUSTOM_HOSTNAME
if [ -z "$CUSTOM_HOSTNAME" ]; then
    CUSTOM_HOSTNAME=$SERVER_HOSTNAME
fi

echo ""
echo "Creating .env file with hostname configuration..."
echo ""

# Create .env file
cat > .env << EOF
# Django Quiz App Configuration
# Generated by setup_hostname.sh

# Security
SECRET_KEY=django-insecure-y0ak1d2)!f_l_gox(\$!r3rg((sm4b4)xqr3ybz&w9&v00t2t8y
DEBUG=True

# Host Configuration
# Allow connections from hostname and IP address
ALLOWED_HOSTS=${CUSTOM_HOSTNAME}.local,${CUSTOM_HOSTNAME},${IP_ADDRESS},localhost,127.0.0.1

# Site URL - Base URL for the application
SITE_URL=http://${CUSTOM_HOSTNAME}.local:8000

# Database Configuration
DB_NAME=quiz_system_db
DB_USER=postgres
DB_PASSWORD=4545
DB_HOST=localhost
DB_PORT=5432

# Email Configuration
DEFAULT_FROM_EMAIL=noreply@schoolsystem.com
EOF

echo ".env file created successfully!"
echo ""
echo "Configuration:"
echo "  - Hostname: $CUSTOM_HOSTNAME"
echo "  - IP Address: $IP_ADDRESS"
echo "  - Site URL: http://${CUSTOM_HOSTNAME}.local:8000"
echo ""
echo "Next steps:"
echo "  1. Make sure python-dotenv is installed: pip install python-dotenv"
echo "  2. Run the server with: python manage.py runserver 0.0.0.0:8000"
echo "  3. Access from client: http://${CUSTOM_HOSTNAME}.local:8000"
echo ""
echo "Note: If hostname doesn't resolve, add this to client's /etc/hosts file:"
echo "  $IP_ADDRESS    ${CUSTOM_HOSTNAME}.local"
echo ""




