@echo off
REM Quick setup script for hostname configuration on Windows
REM This script helps you configure the Django app to use a hostname

echo ========================================
echo Django Quiz App - Hostname Configuration
echo ========================================
echo.

REM Get hostname
for /f "tokens=*" %%i in ('hostname') do set SERVER_HOSTNAME=%%i
echo Detected hostname: %SERVER_HOSTNAME%
echo.

REM Get IP address
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"IPv4 Address"') do (
    set IP_ADDRESS=%%a
    goto :found_ip
)
:found_ip
set IP_ADDRESS=%IP_ADDRESS:~1%
echo Detected IP address: %IP_ADDRESS%
echo.

REM Prompt for custom hostname
set /p CUSTOM_HOSTNAME="Enter your desired hostname (or press Enter to use %SERVER_HOSTNAME%): "
if "%CUSTOM_HOSTNAME%"=="" set CUSTOM_HOSTNAME=%SERVER_HOSTNAME%

echo.
echo Creating .env file with hostname configuration...
echo.

REM Create .env file
(
echo # Django Quiz App Configuration
echo # Generated by setup_hostname.bat
echo.
echo # Security
echo SECRET_KEY=django-insecure-y0ak1d2)!f_l_gox($!r3rg((sm4b4)xqr3ybz&w9&v00t2t8y
echo DEBUG=True
echo.
echo # Host Configuration
echo # Allow connections from hostname and IP address
echo ALLOWED_HOSTS=%CUSTOM_HOSTNAME%.local,%CUSTOM_HOSTNAME%,%IP_ADDRESS%,localhost,127.0.0.1
echo.
echo # Site URL - Base URL for the application
echo SITE_URL=http://%CUSTOM_HOSTNAME%.local:8000
echo.
echo # Database Configuration
echo DB_NAME=quiz_system_db
echo DB_USER=postgres
echo DB_PASSWORD=4545
echo DB_HOST=localhost
echo DB_PORT=5432
echo.
echo # Email Configuration
echo DEFAULT_FROM_EMAIL=noreply@schoolsystem.com
) > .env

echo .env file created successfully!
echo.
echo Configuration:
echo   - Hostname: %CUSTOM_HOSTNAME%
echo   - IP Address: %IP_ADDRESS%
echo   - Site URL: http://%CUSTOM_HOSTNAME%.local:8000
echo.
echo Next steps:
echo   1. Make sure python-dotenv is installed: pip install python-dotenv
echo   2. Run the server with: python manage.py runserver 0.0.0.0:8000
echo   3. Access from client: http://%CUSTOM_HOSTNAME%.local:8000
echo.
echo Note: If hostname doesn't resolve, add this to client's hosts file:
echo   %IP_ADDRESS%    %CUSTOM_HOSTNAME%.local
echo.
pause


