"""
Django settings for quiz_system project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from .env file if it exists
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # python-dotenv not installed, skip loading .env file
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-y0ak1d2)!f_l_gox($!r3rg((sm4b4)xqr3ybz&w9&v00t2t8y")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

# ALLOWED_HOSTS: List of hostnames/IPs that Django will accept requests from
# For hostname access, set this in .env file, e.g.:
# ALLOWED_HOSTS=your-hostname.local,your-server-name,192.168.1.100
# Or use '*' for development (NOT recommended for production)
# Vercel automatically sets VERCEL_URL environment variable
vercel_url = os.environ.get("VERCEL_URL")
if vercel_url:
    ALLOWED_HOSTS = [vercel_url, f"*.{vercel_url}"]
else:
    ALLOWED_HOSTS = [host.strip().lower() for host in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "quiz_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "quiz_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "quiz_app.context_processors.session_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "quiz_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# PostgreSQL Database Configuration
# Supports Supabase connection string format: postgresql://user:password@host:port/dbname
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    # Parse Supabase connection string
    # Format: postgresql://[user]:[password]@[host]:[port]/[database]?[params]
    import urllib.parse as urlparse
    try:
        url = urlparse.urlparse(DATABASE_URL)
        
        # Handle connection pooler URLs (port 6543) vs direct connection (port 5432)
        # Connection pooler is recommended for serverless/Vercel deployments
        port = url.port or ("6543" if "pooler.supabase.com" in url.hostname else "5432")
        
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": url.path[1:] if url.path.startswith("/") else url.path,  # Remove leading '/'
                "USER": url.username,
                "PASSWORD": url.password,
                "HOST": url.hostname,
                "PORT": port,
                "OPTIONS": {
                    "sslmode": "require",  # Supabase requires SSL
                },
                "CONN_MAX_AGE": 600,  # Connection pooling for serverless
            }
        }
    except Exception as e:
        # If parsing fails, log error and fall back to individual env vars
        import sys
        print(f"Warning: Failed to parse DATABASE_URL: {e}", file=sys.stderr)
        DATABASE_URL = None  # Force fallback to individual variables
else:
    # Fallback to individual environment variables
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "quiz_system_db"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "4545"),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
            "OPTIONS": {
                "sslmode": "require" if os.environ.get("DB_HOST") and "supabase.co" in os.environ.get("DB_HOST", "") else "prefer",
            },
        }
    }

# For development, you can use SQLite by uncommenting below:
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "quiz_app" / "static",
]

# Static files root for production (Vercel)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Authentication settings
AUTH_USER_MODEL = "quiz_app.User"

# Login settings
LOGIN_URL = "quiz_app:login"
LOGIN_REDIRECT_URL = "quiz_app:dashboard"
LOGOUT_REDIRECT_URL = "quiz_app:login"

# Superadmin login settings
SUPERADMIN_LOGIN_URL = "quiz_app:superadmin_login"
SUPERADMIN_LOGIN_REDIRECT_URL = "quiz_app:superadmin_dashboard"
SUPERADMIN_LOGOUT_REDIRECT_URL = "quiz_app:superadmin_login"

# Session settings
SESSION_COOKIE_AGE = 3600 * 8  # 8 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email settings (for development)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@schoolsystem.com")

# SITE_URL: Base URL for the application (used in emails, links, etc.)
# For hostname access, set this in .env file, e.g.:
# SITE_URL=http://your-hostname.local:8000
# Or: SITE_URL=http://your-server-name:8000
SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")
